name: CI

on:
  push:
    branches:
      - master
      - v0.*.x
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Python 3.7 with minimal dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-minimal

          - name: Python 3.7
            os: ubuntu-latest
            python: 3.7
            toxenv: py37

          - name: Python 3.7 with Astropy dev
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-astropydev

          - name: Python 3.8 with code coverage
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-cov

          - name: Python 3.8, slow tests with code coverage
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-slow-cov

          - name: Python 3.8 with Numpy dev
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-numpydev

          - name: Python 3.9 with Xarray dev
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-numpydev

          - name: Python 3.9
            os: ubuntu-latest
            python: 3.9
            toxenv: py39

          - name: Python 3.8 (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38
            toxposargs: --durations=50

          - name: Python 3.8 (MacOS X)
            os: macos-latest
            python: 3.8
            toxenv: py38

          - name: Documentation
            os: ubuntu-latest
            python: 3.8
            toxenv: build_docs

          - name: Linters
            os: ubuntu-latest
            python: 3.8
            toxenv: linters

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Install language-pack-fr and tzdata
      if: startsWith(matrix.name, 'Documentation')
      run: sudo apt-get install graphviz pandoc
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v1.5.2
      with:
        file: ./coverage.xml
  build-n-publish:
    name: Packaging
    runs-on: ubuntu-18.04
    needs: tests
    steps:
    - uses: actions/checkout@v4.2.1
    - name: Get history and tags for SCM versioning to work
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7
    - name: Install requirements
      run: |
        pip install --upgrade pip
        pip install setuptools numpy wheel setuptools_scm twine
    - name: Build a binary wheel
      run: python setup.py bdist_wheel
    - name: Build a source tarball
      run: python setup.py sdist
    - name: Twine check
      run: twine check dist/*
    - name: Install PlasmaPy in all variants
      run: |
        pip install --progress-bar off .[all,dev]
        pip install -e .[all,dev]
        python setup.py develop
    - name: Publish distribution, if tagged, 📦 to PyPI
      if: ${{ startsWith(github.ref, 'refs/tags') && !endsWith(github.ref, 'dev') }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_access_token }}
